# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ProfilsOuvrages
                                 A QGIS plugin
 Aide à la saisie de profils d'ouvrgae dans le cadre d'un processus de modélisation 1D
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-23
        copyright            : (C) 2023 by Manuel Collongues / Cerema
        email                : manuel.collongues@cerema.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ProfilsOuvrages class from file ProfilsOuvrages.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .profils_ouvrages import ProfilsOuvrages
    return ProfilsOuvrages(iface)
