# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\manuel.collongues\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\profils_ouvrages\profils_ouvrages_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfilsOuvragesDialogBase(object):
    def setupUi(self, ProfilsOuvragesDialogBase):
        ProfilsOuvragesDialogBase.setObjectName("ProfilsOuvragesDialogBase")
        ProfilsOuvragesDialogBase.resize(926, 309)
        self.pb_selec_dossier_profils = QtWidgets.QPushButton(ProfilsOuvragesDialogBase)
        self.pb_selec_dossier_profils.setGeometry(QtCore.QRect(120, 30, 301, 23))
        self.pb_selec_dossier_profils.setObjectName("pb_selec_dossier_profils")
        self.le_dossier_profils_pdf = QtWidgets.QLineEdit(ProfilsOuvragesDialogBase)
        self.le_dossier_profils_pdf.setGeometry(QtCore.QRect(430, 30, 431, 20))
        self.le_dossier_profils_pdf.setObjectName("le_dossier_profils_pdf")
        self.label = QtWidgets.QLabel(ProfilsOuvragesDialogBase)
        self.label.setGeometry(QtCore.QRect(120, 80, 301, 16))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.pb_extraire_distcote = QtWidgets.QPushButton(ProfilsOuvragesDialogBase)
        self.pb_extraire_distcote.setGeometry(QtCore.QRect(130, 190, 291, 61))
        self.pb_extraire_distcote.setObjectName("pb_extraire_distcote")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(ProfilsOuvragesDialogBase)
        self.plainTextEdit.setGeometry(QtCore.QRect(433, 190, 431, 61))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.cb_liste_couches = QtWidgets.QComboBox(ProfilsOuvragesDialogBase)
        self.cb_liste_couches.setGeometry(QtCore.QRect(430, 80, 211, 22))
        self.cb_liste_couches.setObjectName("cb_liste_couches")
        self.cb_liste_champs = QtWidgets.QComboBox(ProfilsOuvragesDialogBase)
        self.cb_liste_champs.setGeometry(QtCore.QRect(430, 120, 211, 22))
        self.cb_liste_champs.setObjectName("cb_liste_champs")
        self.label_2 = QtWidgets.QLabel(ProfilsOuvragesDialogBase)
        self.label_2.setGeometry(QtCore.QRect(120, 120, 301, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.pb_update = QtWidgets.QPushButton(ProfilsOuvragesDialogBase)
        self.pb_update.setGeometry(QtCore.QRect(700, 80, 91, 61))
        self.pb_update.setObjectName("pb_update")
        self.label_3 = QtWidgets.QLabel(ProfilsOuvragesDialogBase)
        self.label_3.setGeometry(QtCore.QRect(40, 70, 21, 31))
        self.label_3.setStyleSheet("font: 75 20pt \"Arial\";\n"
"color: rgb(239, 119, 87);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ProfilsOuvragesDialogBase)
        self.label_4.setGeometry(QtCore.QRect(40, 110, 21, 31))
        self.label_4.setStyleSheet("font: 75 20pt \"Arial\";\n"
"color: rgb(239, 119, 87);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(ProfilsOuvragesDialogBase)
        self.label_5.setGeometry(QtCore.QRect(40, 190, 21, 31))
        self.label_5.setStyleSheet("font: 75 20pt \"Arial\";\n"
"color: rgb(239, 119, 87);")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(ProfilsOuvragesDialogBase)
        QtCore.QMetaObject.connectSlotsByName(ProfilsOuvragesDialogBase)

    def retranslateUi(self, ProfilsOuvragesDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ProfilsOuvragesDialogBase.setWindowTitle(_translate("ProfilsOuvragesDialogBase", "Profils ouvrages"))
        self.pb_selec_dossier_profils.setText(_translate("ProfilsOuvragesDialogBase", "Convertir des PDF en images"))
        self.label.setText(_translate("ProfilsOuvragesDialogBase", "Nom de la couche de dessin des profils :"))
        self.pb_extraire_distcote.setText(_translate("ProfilsOuvragesDialogBase", "Extraire les couples (distance, cote)"))
        self.label_2.setText(_translate("ProfilsOuvragesDialogBase", "Nom du champ identifiant chaque profil :"))
        self.pb_update.setText(_translate("ProfilsOuvragesDialogBase", "Actualiser la \n"
"liste des \n"
"couches"))
        self.label_3.setText(_translate("ProfilsOuvragesDialogBase", "1"))
        self.label_4.setText(_translate("ProfilsOuvragesDialogBase", "2"))
        self.label_5.setText(_translate("ProfilsOuvragesDialogBase", "3"))
