# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\manuel.collongues\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\profils_ouvrages\profils_ouvrages_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfilsOuvragesDialogBase(object):
    def setupUi(self, ProfilsOuvragesDialogBase):
        ProfilsOuvragesDialogBase.setObjectName("ProfilsOuvragesDialogBase")
        ProfilsOuvragesDialogBase.resize(931, 300)
        self.button_box = QtWidgets.QDialogButtonBox(ProfilsOuvragesDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.pb_selec_dossier_profils = QtWidgets.QPushButton(ProfilsOuvragesDialogBase)
        self.pb_selec_dossier_profils.setGeometry(QtCore.QRect(50, 30, 301, 23))
        self.pb_selec_dossier_profils.setObjectName("pb_selec_dossier_profils")
        self.le_dossier_profils_pdf = QtWidgets.QLineEdit(ProfilsOuvragesDialogBase)
        self.le_dossier_profils_pdf.setGeometry(QtCore.QRect(360, 30, 431, 20))
        self.le_dossier_profils_pdf.setObjectName("le_dossier_profils_pdf")
        self.le_couche_dessin = QtWidgets.QLineEdit(ProfilsOuvragesDialogBase)
        self.le_couche_dessin.setGeometry(QtCore.QRect(360, 80, 431, 20))
        self.le_couche_dessin.setObjectName("le_couche_dessin")
        self.label = QtWidgets.QLabel(ProfilsOuvragesDialogBase)
        self.label.setGeometry(QtCore.QRect(50, 80, 301, 16))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.pb_extraire_distcote = QtWidgets.QPushButton(ProfilsOuvragesDialogBase)
        self.pb_extraire_distcote.setGeometry(QtCore.QRect(54, 130, 291, 23))
        self.pb_extraire_distcote.setObjectName("pb_extraire_distcote")
        self.le_dossier_couple_distance_cote = QtWidgets.QLineEdit(ProfilsOuvragesDialogBase)
        self.le_dossier_couple_distance_cote.setGeometry(QtCore.QRect(360, 130, 431, 20))
        self.le_dossier_couple_distance_cote.setObjectName("le_dossier_couple_distance_cote")

        self.retranslateUi(ProfilsOuvragesDialogBase)
        self.button_box.accepted.connect(ProfilsOuvragesDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(ProfilsOuvragesDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ProfilsOuvragesDialogBase)

    def retranslateUi(self, ProfilsOuvragesDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ProfilsOuvragesDialogBase.setWindowTitle(_translate("ProfilsOuvragesDialogBase", "Profils ouvrages"))
        self.pb_selec_dossier_profils.setText(_translate("ProfilsOuvragesDialogBase", "Sélectionner dossier contenant les profils au format PDF"))
        self.label.setText(_translate("ProfilsOuvragesDialogBase", "Nom de la couche de dessin des profils :"))
        self.pb_extraire_distcote.setText(_translate("ProfilsOuvragesDialogBase", "Extraire les couples (distance, cote) dans ce dossier :"))
